name: Update Keymap SVGs
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  render:
    permissions:
      contents: write
    uses: ./.github/workflows/draw-zmk.yml
    with:
      keymap_patterns: "config/*.keymap"        # path to the keymaps to parse
      config_path: "keymap_drawer.config.yaml"  # config file, ignored if not exists
      output_folder: "svg"                      # path to save produced SVGs
      parse_args: ""  # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      draw_args: ""   # map of extra args to pass to `keymap draw`, e.g. "corne:'-k corne_rotated' cradio:'-k paroxysm'"
      commit_message: "Update Keymap SVGs"